const DIR = "http://192.168.1.79:3001";
export const BST = `${DIR}/Negocios`;
export const SCT = `${DIR}/Clasificacion`;
export const ADP = `${DIR}/agregar/producto`;
export const TEC = `${DIR}/Tecnologias`;
export const TAD = `${DIR}/TiposDom`;
export const AAS = `${DIR}/Agregar/domicilio`;
export const ABT = `${DIR}/Agregar/Negocio`;
export const AAT = `${DIR}/Agregar/TipoDomicilio`;
export const ATH = `${DIR}/Agregar/Tecnologia`;
export const ACS = `${DIR}/Agregar/Clasificacion`;
export const PBS = `${DIR}/proveedor/productos/`;
export const SBI = `${DIR}/proveedor/`;
export const ADS = `${DIR}/Agregar/proveedor`;
export const ACA = `${DIR}/Agregar/contacto`;
export const SBF = `${DIR}/proveedores`;
export const PFF = `${DIR}/productos`;
export const PBI = `${DIR}/producto/`;
export const APS = `${DIR}/Asignar/Producto`;
export const SBP = `${DIR}/Proveedor/Producto/`;
export const USP = `${DIR}/Actualizar/Relacion`;
export const SAF = `${DIR}/proveedor/domicilios/`;
export const SAC = `${DIR}/proveedor/domicilio/contactos/`;
export const DAS = `${DIR}/Borrar/Domicilio/`;
export const SPS = `${DIR}/Producto/Proveedores/`;
export const UPF = `${DIR}/Actualizar/Producto`;
export const UBT = `${DIR}/Actualizar/Negocio`;
export const UTH = `${DIR}/Actualizar/Tecnologia`;
export const UCS = `${DIR}/Actualizar/Clasificacion`;
export const UAT= `${DIR}/Actualizar/TipoDomicilio`;
export const UCA= `${DIR}/Actualizar/Contacto`
export const AUS= `${DIR}/Registrar/usuario`
export const AUT= `${DIR}/Autenticar`
